NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

[DOCUMENTATION]
ORG_NAME="LUMENGOLDUSD"
ORG_URL="https://lumengoldusd.netlify.app"
ORG_DESCRIPTION="LUMENGOLDUSD Token on the Stellar Network"

[[CURRENCIES]]
code="LUMENGOLDUSD"
issuer="GCO7DST6GPLM47NVHGCKPEOYEWE2IZBFGKPI3MXIZPQ5EIY7Q3AGAYZ4"
display_decimals=2
name="Lumen Gold USD"
description="LUMENGOLDUSD Token on the Stellar Network"
image = "https://lumengoldusd.netlify.app/icon.png"
is_asset_anchored=false
status="live"
